### ISSUE TITLE
Add-In to Article Submission

### ISSUE THREAD

**Issue by Amazingred** [HTS-Codeart/blog#4]
Having the option to SAVE ARTICLE without posting it would be a great plus.  Since syntax and tags may be an issue it would be nice for users to be able to type their articles directly into the submissions page and be able to save them as they go to avoid session issues or making edits after PASTING into the submission form.

Still picking up site dev as I go so I'll have to do some research on how to include this if its possible without too much hassle.

**Comment by mShred** [comment]
Thought you was dead.

**Comment by Amazingred** [comment]
Nah, The past year has been a pain in the rump  Stuffs just starting to get back to normal.

**Comment by Ninjex** [comment]
It would be great to see you around again. Come visit when you have spare time, albeit a busy season for a lot of us right now.

**Comment by mShred** [comment]
hai guys
